name: "Add PR/Issue Labels"
description: "Add labels on Pull Requests or Issues"
inputs:
  labels:
    description: "Labels to add"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "plus"
  color: "purple"
